target 'EventsTreeiOSExample' do
  use_frameworks!
  platform :ios, '9.0'

  pod 'EventsTree', '~> 0.1'
  pod 'AMPopTip', '2.1.6'

  target 'EventsTreeiOSExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
